# Generated by Django 5.0.7 on 2024-07-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instagram_id',
            field=models.CharField(blank=True, default='s', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_id',
            field=models.CharField(blank=True, default='s', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_id',
            field=models.CharField(blank=True, default='s', max_length=120, null=True),
        ),
    ]
