# Generated by Django 5.0.7 on 2024-07-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_instagram_id_profile_linkedin_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='follow',
            new_name='follows',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='default_profile.png', upload_to='profile_images'),
        ),
    ]
