# Generated by Django 5.0.7 on 2024-07-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_audio_file_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='post_audio_files'),
        ),
    ]
