# Generated by Django 5.0.7 on 2024-08-01 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_content_alter_post_image_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='date',
            new_name='created',
        ),
    ]
